---

# To enable New Relic, make sure you've uncommented the `wevote-private.yml`
# env vars and the two `newrelic` roles.
#
# Because the private env vars file is encrypted with Ansible Vault, you'll also
# need to uncomment `ansible.ask_vault_pass = true` in the Vagrantfile.

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  become: yes
  become_user: root
  remote_user: vagrant
  vars:
    update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant.yml
    # - env_vars/wevote-private.yml

  roles:
    - base
    - avahi
    - db
    - web
    - nginx
    # - newrelic
    # - { role: nrinfragent, nrinfragent_license_key: "{{ new_relic_key }}"  }
    # - rabbitmq
    # - celery
