---

- name: Install New Relic Python agent
  pip: virtualenv={{ virtualenv_path }} name=newrelic
  tags: newrelic

- name: Ensure local /etc exists
  file:
    state: directory
    path: /webapps/{{ application_name }}/etc
    mode: 0755

- name: Generate New Relic APM config
  template: src=newrelic.ini.j2
            dest={{ virtualenv_path }}/etc/newrelic.ini
            mode=0664

- name: Generate New Relic-enabled Gunicorn start script
  template: src=gunicorn_start.j2
            dest={{ virtualenv_path }}/bin/gunicorn_start
            mode=0755
            force=yes
            owner=wevoteserver
            group=webapps
  notify: restart application
