---

- name: Install New Relic Python agent
  pip:
    name: newrelic
  tags: newrelic

- name: Ensure local /etc exists
  file:
    state: directory
    path: /webapps/{{ application_name }}/etc
    mode: 0755

- name: Generate New Relic APM config
  template: src=newrelic.ini.j2
            dest=/webapps/{{ application_name }}/etc/newrelic.ini
            mode=0664

- name: Update Gunicorn start script
  replace:
    dest={{ virtualenv_path }}/bin/gunicorn_start
    regexp='exec gunicorn'
    replace='NEW_RELIC_PROCESS_HOST_DISPLAY_NAME="{{ project_name }} (Dev)" NEW_RELIC_CONFIG_FILE=/webapps/{{ application_name }}/etc/newrelic.ini exec newrelic-admin run-program gunicorn'
    backup=yes

- name: Re-read the Supervisor config files & restart Gunicorn
  supervisorctl: name={{ application_name }} state=present
  notify: restart application
