---

git_repo: https://github.com/mshmsh5000/WeVoteServer.git

project_name: WeVoteServer
application_name: wevoteserver

# The name of the module to start Django with (may be same as application name).
# This is what gets passed to Gunicorn as '{{ django_module_name }}.wsgi'.
django_module_name: config

# Note that this PPA doesn't guarantee timely updates in case of security issues.
# Simply remove these two vars below if you prefer to use the official PPA and
# default Python version that came with your Linux distro.
#
# More info here: https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes
enable_deadsnakes_ppa: yes
virtualenv_python_version: python3.6
